export enum ERROR_MESSAGES {
    BOOK_NOT_FOUND = 'THERE WAS AN ERROR DURING BOOK DATA FETCHING',
    CATEGORY_NOT_FOUND = 'THERE WAS AN ERROR DURING CATEGORY FETCHING PHASE.',
    LACK_OF_BUY_OPTIONS = 'SELECTED BOOK NOT HAS ANY BUYING OPTIONS.',
}